server:
  port: 7000
  servlet:
    context-path: /mmall-file

spring:
  application:
    name: eureka-client-mmall-file

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
